version: "3"

volumes:
  db-data:

services:
  dev-db:
    image: postgres:16
    env_file: .env.local
    restart: always
    ports:
      - "5432:5432"
  test-db:
    image: postgres:16
    env_file: .env.test
    restart: always
    ports:
      - "5433:5432"
